account_info:
     phone: 15659267036
     password: 123456
     name: '闹p丫你'

flag:
    compare_flag: 0

soa_config:
    env: 0
    soa_client:
        "tqmq": "http://tqmq.test.k8s.taqu.cn/v2/Soa/"
        "bbs": "http://bbs.test.k8s.taqu.cn/v5/Soa/"
        "ui_auto": "http://j9.test.k8s.taqu.cn/tq-qtp/api"
    soa_system:
        "tqmq": "php"
        "bbs": "php"
        "ui_auto": "java"

desired_caps:
    platform_name: "Android"
    app_package: "com.xingjiabi.shengsheng"
    app_activity: "com.xingjiabi.shengsheng.app.SplashActivity"
    noreset: False
    automationName: "uiautomator2"

emulator:
    device_name: 127.0.0.1:62025
    device_version: 5.1.1

http:
    url: "http://j9.test.k8s.taqu.cn/"

linux:
    host_name: 10.10.60.228
    username: root
    password: HAibao123!@
    port: 22
    file_path: /data/html/qtp/

apk:
   path: '//10.10.5.249/packages/android迭代安装包/Taqu-Jenkins/auto-test'

send_msg:
    sender: "137237569@qq.com"
    password: "zubaezoxeelvbhdd"
    receivers: ["lushan@taqu.cn"]

email:
    url: "http://j9.test.k8s.taqu.cn/tq-qtp/index"
    host: "smtp.qq.com"
    port: 25

devices:
  - device: 127.0.0.1:62025
    port: 4723
  - device: 127.0.0.1:62026
    port: 4724
  - device: 127.0.0.1:62027
    port: 4725
  - device: 127.0.0.1:62028
    port: 4726

phone_pool:
  - [12900000001, 12900000002, 12900000003]
  - [12900000004, 12900000005, 12900000006]
  - [12900000007, 12900000008, 12900000009]
